# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - SampleWebAppHubertCiebiada

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_a24c92b4ba5249119d132c6cdc7b89f2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b3190f74ea2a480aab11a9ea4761f096 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        context: "./SampleApp"
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_a24c92b4ba5249119d132c6cdc7b89f2 }}/sampleapp/sampleapp:latest
        file: ./SampleApp/SampleWebApp/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'SampleWebAppHubertCiebiada'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ffbf46b1b9864aa19f9687eb495f8879 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_a24c92b4ba5249119d132c6cdc7b89f2 }}/ghcr.io/hubertciebiada/samplewebapp:latest'